projects:
  api:
    schemaPath: api/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  db:
    schemaPath: prisma/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
